import React from 'react';
import bg from '../../Assets/Images/Wallpaper10.jpg';

const Aboutus=()=>{
    return(
        <div>
        <img src={bg} class="img-fluid w-100" alt="Responsive image"/>
           <div class="container text-justify mt-4">
               <h2>About Us</h2>
               <p>WE @ RR ORTHOCARE SERVING THE FOOT AND ANKLE COMMUNITY SINCE THE PAST FEW YEARS</p>
               <p>RR ORTHO IS DEDICATED TO BEING THE LEADING PROVIDER OF DIABETIC,ORTHOPETIC,CUMSOM MADE COMPUTERIZED INSOLES AND WOUND CARE SOLUTIONS TO THE FOOT AND ANKLE COMMUNITY.</p>
               <p>BEYOND THE MANUFACTURE AND SALE OF VARIOUS PRODUCTS AND SERVICES.WE ARE DEDICATED TO WORK ON NEW PRODUCT DEVELOPMENTS AND SUPPORT WITH GREAT R AND D TO MEET THE REQUIREMENTS OF THE END USER OF THE PRODUCT IN MAKING THEM COST EFFECTIVE AND LONG LASTING.</p>
               <p>WE STRIVE TO BRING THE LATEST IN TECHNOLOGY, SKILL AND INNOVATIONS IN THE FIELD OF PROSTHETICS AND ORTHOTICS</p>
               <p>OUR MISSION IS TO PROVIDE A COMPLETE QUALITY FOOT CARE TO EACH AND EVERY PATIENT IN INDIA AT AN AFFORDABLE PRICE.</p>
               <p>WE OFFER STATE-OF-THE-ART TECHNOLOGY, QUALITY AND SERVICE TO PATIENTS THROUGH THE USE OF ADVANCED DIGITIZING SYSTEMS, LATEST MACHINERIES AND A WORLD CLASS GAIT TRAINING AREA. OUR CLINICIANS ARE HIGHLY TRAINED, QUALIFIED AND ARE AMERICAN BOARD CERTIFIED WHO PAY SPECIAL ATTENTION TO A PATIENT’S NEEDS AND THEIR CONCERNS. THROUGH RESEARCH AND EDUCATION WE STRIVE TO ADVANCE THE FIELD OF FOOT AND ANKLE COMMUNITY.</p>
            </div>
        </div>
    )
}
export default Aboutus;